### ISSUE TITLE
"[lsc:Error] StdErr from dart_language_server" when closing Vim

### ISSUE THREAD

**Issue by leonsenft** [natebosch/dart_language_server#65]
I'm seeing the following error when closing a Vim session.

I believe this occurs when I have a buffer open for a directory (opened via `:Ex`/`:Vex`/`:Sex`).

I've redacted `<root>` (from the file path) but can provide it privately if needed to diagnose this further.

```
[lsc:Error] StdErr from dart_language_server: Uncaught Exception: [Analyzer RequestError method: analysis.updateContent, code: INVALID_FILE_PATH_FORMAT, message: Invalid file path format: <root>/third_party/dart_src/angular/angular/lib/src/core/linker/]
[lsc:Error] StdErr from dart_language_server: #0      AnalysisServerAdapter.textDocumentDidClose.<anonymous closure> (package:dart_language_server/src/shim.dart:172:7)
[lsc:Error] StdErr from dart_language_server: <asynchronous suspension>
[lsc:Error] StdErr from dart_language_server: #1      Pool.withResource (package:pool/pool.dart:127:28)
[lsc:Error] StdErr from dart_language_server: <asynchronous suspension>
[lsc:Error] StdErr from dart_language_server: #2      PerFilePool.lock (package:dart_language_server/src/utils/per_file_pool.dart:14:12)
[lsc:Error] StdErr from dart_language_server: #3      AnalysisServerAdapter.textDocumentDidClose (package:dart_language_server/src/shim.dart:171:19)
[lsc:Error] StdErr from dart_language_server: #4      StdIOLanguageServer._fileHandlingMethods.<anonymous closure> (package:dart_language_server/src/protocol/language_server/server.dart:76:15)
[lsc:Error] StdErr from dart_language_server: #5      StdIOLanguageServer._registerNotification.<anonymous closure> (package:dart_language_server/src/protocol/language_server/server.dart:63:42)
[lsc:Error] StdErr from dart_language_server: #6      Server._handleSingleRequest (package:json_rpc_2/src/server.dart:164:30)
[lsc:Error] StdErr from dart_language_server: <asynchronous suspension>
[lsc:Error] StdErr from dart_language_server: #7      Server._handleRequest (package:json_rpc_2/src/server.dart:140:24)
[lsc:Error] StdErr from dart_language_server: <asynchronous suspension>
[lsc:Error] StdErr from dart_language_server: #8      _rootRunUnary (dart:async/zone.dart:1132:38)
[lsc:Error] StdErr from dart_language_server: #9      _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[lsc:Error] StdErr from dart_language_server: #10     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[lsc:Error] StdErr from dart_language_server: #11     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
[lsc:Error] StdErr from dart_language_server: #12     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
[lsc:Error] StdErr from dart_language_server: #13     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
[lsc:Error] StdErr from dart_language_server: #14     _StreamController._add (dart:async/stream_controller.dart:640:7)
[lsc:Error] StdErr from dart_language_server: #15     _StreamController.add (dart:async/stream_controller.dart:586:5)
[lsc:Error] StdErr from dart_language_server: #16     Peer.listen.<anonymous closure> (package:json_rpc_2/src/peer.dart:93:36)
[lsc:Error] StdErr from dart_language_server: #17     _rootRunUnary (dart:async/zone.dart:1132:38)
[lsc:Error] StdErr from dart_language_server: #18     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[lsc:Error] StdErr from dart_language_server: #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[lsc:Error] StdErr from dart_language_server: #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
[lsc:Error] StdErr from dart_language_server: #21     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
[lsc:Error] StdErr from dart_language_server: #22     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
[lsc:Error] StdErr from dart_language_server: #23     _ForwardingStream._handleData (dart:async/stream_pipe.dart:98:10)
[lsc:Error] StdErr from dart_language_server: #24     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
[lsc:Error] StdErr from dart_language_server: #25     _rootRunUnary (dart:async/zone.dart:1132:38)
[lsc:Error] StdErr from dart_language_server: #26     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[lsc:Error] StdErr from dart_language_server: #27     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[lsc:Error] StdErr from dart_language_server: #28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
[lsc:Error] StdErr from dart_language_server: #29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
[lsc:Error] StdErr from dart_language_server: #30     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:132:11)
[lsc:Error] StdErr from dart_language_server: #31     _MapStream._handleData (dart:async/stream_pipe.dart:232:10)
[lsc:Error] StdErr from dart_language_server: #32     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:164:13)
[lsc:Error] StdErr from dart_language_server: #33     _rootRunUnary (dart:async/zone.dart:1132:38)
[lsc:Error] StdErr from dart_language_server: #34     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[lsc:Error] StdErr from dart_language_server: #35     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[lsc:Error] StdErr from dart_language_server: #36     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
[lsc:Error] StdErr from dart_language_server: #37     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:263:7)
[lsc:Error] StdErr from dart_language_server: #38     _SyncStreamController._sendData (dart:async/stream_controller.dart:764:19)
[lsc:Error] StdErr from dart_language_server: #39     _StreamController._add (dart:async/stream_controller.dart:640:7)
[lsc:Error] StdErr from dart_language_server: #40     _StreamController.add (dart:async/stream_controller.dart:586:5)
[lsc:Error] StdErr from dart_language_server: #41     tap.<anonymous closure> (package:stream_transform/src/tap.dart:31:12)
[lsc:Error] StdErr from dart_language_server: #42     _StreamTransformer.bind.<anonymous closure>.<anonymous closure> (package:stream_transform/src/from_handlers.dart:59:47)
[lsc:Error] StdErr from dart_language_server: #43     _rootRunUnary (dart:async/zone.dart:1132:38)
[lsc:Error] StdErr from dart_language_server: #44     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
[lsc:Error] StdErr from dart_language_server: #45     _CustomZone.runUnaryGuarded (dart:async/zone.dart:931:7)
[lsc:Error] StdErr from dart_language_server: #46     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:336:11)
[lsc:Error] StdErr from dart_language_server: #47     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
[lsc:Error] StdErr from dart_language_server: #48     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:707:11)
[lsc:Error] StdErr from dart_language_server: #49     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:667:7)
[lsc:Error] StdErr from dart_language_server: #50     _rootRun (dart:async/zone.dart:1120:38)
[lsc:Error] StdErr from dart_language_server: #51     _CustomZone.run (dart:async/zone.dart:1021:19)
[lsc:Error] StdErr from dart_language_server: #52     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
[lsc:Error] StdErr from dart_language_server: #53     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
[lsc:Error] StdErr from dart_language_server: #55     _CustomZone.run (dart:async/zone.dart:1021:19)
[lsc:Error] StdErr from dart_language_server: #56     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
[lsc:Error] StdErr from dart_language_server: #57     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
[lsc:Error] StdErr from dart_language_server: #58     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
[lsc:Error] StdErr from dart_language_server: #59     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
[lsc:Error] StdErr from dart_language_server: #60     _runPendingImmediateCallback (dart:isolate/runtime/lib/isolate_patch.dart:115:13)
[lsc:Error] StdErr from dart_language_server: #61     _RawReceivePortImpl._handleMessage (dart:isolate/runtime/lib/isolate_patch.dart:172:5)
```

**Comment by natebosch** [comment]
I think I saw the same thing the other day and I never dug in - are you using `vim-lsc`? I suspect the bug _might_ be in that. We shouldn't be sending anything about those directories to the server since they aren't files with filetype `dart`...

Can you reliably repro this?

**Comment by leonsenft** [comment]
Yes, I'm using vim-lsc + dart_language_server. I tried updating both (there was a vim-lsc update, but it didn't make a difference).

Yes this is reproducible.

1. Open a `.dart` file.
2. Wait for analysis results.
3. Open the file explorer (`:Ex`).
4. Now select a Dart file from the explorer, *or* return to your previous buffer in which the original Dart file is loaded.
4. Now regardless of what you do, upon exiting Vim the error will occur.

**Comment by natebosch** [comment]
Cool, I can repro with those steps. I'll dig in soon.

**Comment by leonsenft** [comment]
Thanks!

**Comment by natebosch** [comment]
I fixed a bug in https://github.com/natebosch/vim-lsc/commit/e1d20173c44825c792589d680599faf24eea1e08 where it was sending a `didClose` for these buffers unnecessarily.

It's plausible there is still something that _should_ be done here to handle similar bugs in clients, but since this client will be going away soon in favor of the analysis server in the SDK I don't think I'll bother to dig deeper.
